# python pandas lib 2주차

# 배열의 인덱싱

In [1]:
# 배열의 인덱싱
import numpy as np

np_arr = np.array([170,270,370,470])

# 첫번째 원소 참조
print(np_arr[0])

# 두번째 원소 참조
print(np_arr[1])

# 세번째 원소 참조
print(np_arr[2])

# 인덱스 범위에서 벗어난 참조는?
#print(np_arr[4])



170
270
370


In [2]:

np_arr = np.array([10,20,30,40])
print(np_arr[2]+np_arr[3])

# 원소가 문자열인 경우?
np_arr = np.array(['10','20','30','40'])
print(int(np_arr[2]) + int(np_arr[3]))

# 배열 a,b에 대해 사칙연산 바로 표현

a1 = np.array([10,20,30,40])
a2 = np.array([10,20,30,40])
print (a1*a2)

70
70
[ 100  400  900 1600]


In [3]:
# 6p 배열 원소 참조 계산

np_arr = np.array([190,290,390,490])
print(np_arr[2] + np_arr[3])

# 원소가 문자열인 경우?
np_arr = np.array(['190','290','390','490'])
print(int(np_arr[2]) + int(np_arr[3]))

#2차원 배열 참조
np_arr = np.array([[171,272,373,474,575],[616,717,818,919,111]])
print('1행의 2열 원소 : ',np_arr[-2,-4]) #print('1행의 2열 원소 : ',np_arr[0,1])
print('2행의 5열 원소 : ',np_arr[1,4]) #print('2행의 5열 원소 : ',np_arr[-1,-1])

#3차원 배열 참조
np_arr = np.array([[[101,202,303],[111,222,333],[123,456,789]]])
print('1면,2행,3열 원소 : ',np_arr[0,1,2])

#음수 인덱스 값 사용
np_arr = np.array([[10,20,30,40,50],[66,77,88,99,100]])
print('2행의 마지막 원소 : ',np_arr[1,-1])

# 문제 : 다음 배열에서 20을 출력하도록 만들어보셈
np_arr = np.array = ([10,20,30])
print(np_arr[1])




880
880
1행의 2열 원소 :  272
2행의 5열 원소 :  111
1면,2행,3열 원소 :  333
2행의 마지막 원소 :  100
20


# 배열 슬라이싱
기본 형태 : [start:end] or [start:end:step]
생략 가능 부분 : 시작 인덱스 0, 마지막 인덱스, step이 1인 경우

In [11]:
import numpy as np

np_arr =np.array([1,2,3,4,5,6,7])

#전체 원소 출력
print(np_arr[:])
print(np_arr[:6])
print(np_arr[0:])

#마지막 3개 원소 출력하기
print(np_arr[-3:])
print(np_arr[-3:7])

#짝수 번째 표시
print(np_arr[1::2])

# 2차원 배열 슬라이싱
np_arr = np.array([[101,202,303,404,505],[111,222,333,444,555]])
print('두번째 행의 2열부터 4열까지 : ',np_arr[1,1:4])
print('첫번째 행부터 두번째행에 대해 각 행의 2열 : ',np_arr[0:2,1])
print('첫번째 행부터 두번째 행에 대해 2열부터 4열까지 : ',np_arr[0:2,1:4])

[1 2 3 4 5 6 7]
[1 2 3 4 5 6]
[1 2 3 4 5 6 7]
[5 6 7]
[5 6 7]
[2 4 6]
두번째 행의 2열부터 4열까지 :  [222 333 444]
첫번째 행부터 두번째행에 대해 각 행의 2열 :  [202 222]
첫번째 행부터 두번째 행에 대해 2열부터 4열까지 :  [[202 303 404]
 [222 333 444]]


# python과 numpy의 데이터 타입
Python
: string - ex) "abcd"
: integer -ex) -1,0,1
: float -ex) 10.2, 4.2
: boolean -ex) True, False
: complex -ex) 10.0+20.0j, 1.8+4.2j

Numpy
: i - 정수(integer)
: b - 불(boolean)
: u - 부호없는 정수(unsigned integer)
: f - 실수(float)
: c - 복소수(complex float)
: m - 시간(timedelta)
: M - 날짜 시간(datetime)
: O - 객체(object)
: S - 문자열(string)
: U - 유니코드(unicode string)
: V - 여러 데이터 타입을 표현할 수 있는 고정단위 메모리(void)

In [12]:
# 넘파이 배열 객체의 dtype 사용
np_arr = np.array([170,270,370,470])
print(np_arr.dtype)

np_arr = np.array(['사과','배','복숭아'])
print(np_arr.dtype)

int32
<U3


In [13]:
# 넘파이 array() 메서드의 dtype에 생성한 배열 원소에 대한 타입 기호 지정
np_arr = np.array([170,270,370,470], dtype='S') # S 는 string
print(np_arr)
print(np_arr.dtype)

#실습 1 : 출력된 데이터 타입 분석해보기
#실습 2 : dtype = 'S'인 경우와 'U'인 경우의 차이점 찾아보기
#실습 3 : i,fu,f,S,U 는 데이터의 크기를 줄 수 있음

# 위 예제에서 20 을 2222로 변경하고 dtype ='S'를 dtype='S3'로 변경 후 실행해 결과 분석하기

#데이터 타입을 변경할 수 없는 경우 어떤 일이?

np_arr=np.array(['aa','20','30'],dtype='i')

[b'170' b'270' b'370' b'470']
|S3


ValueError: invalid literal for int() with base 10: 'aa'

In [15]:
#기 정의된 배열의 데이터 타입 변경(1)
np_arr=np.array([10.1,20,1,30.1])

newarr = np_arr.astype('i')
print(newarr)
print(newarr.dtype)

# 기 정의된 배열의 데이터 타입 변경(2)
np_arr=np.array([10.1,20,1,30.1])

newarr = np_arr.astype(int)
print(newarr)
print(newarr.dtype)

#정수를 불 타입으로 변경
np_arr=np.array([10,0,30,-10])

newarr = np_arr.astype(bool)
print(newarr)
print(newarr.dtype)




[10 20  1 30]
int32
[10 20  1 30]
int32
[ True False  True  True]
bool


# q배열의 copy와 view
copy : 원본의 데이터 저장 공간과 다른 저장 공간을 할당해 배열 원소 복사, side-effect없음
view : 원본의 데이터 저장 공간을 참조, side-effect발생

In [16]:
# 배열 copy 예시
np_arr=np.array([101,202,303,404,505])
x = np_arr.copy()
np_arr[0] = 129
print(np_arr)
print(x)

[129 202 303 404 505]
[101 202 303 404 505]


In [17]:
# 배열 view 예시(참조본 변경했을 경우 변화 확인)

np_arr=np.array([170,270,370,470])
x = np_arr.view()
x[0] = 129
print(np_arr)
print(x)
 

[129 270 370 470]
[129 270 370 470]


In [18]:
# 배열 view 예시(원본 변경했을 경우 변화 확인)

np_arr=np.array([170,270,370,470,570])
x = np_arr.view()
np_arr[0] = 129
print(np_arr)
print(x)
 

[129 270 370 470 570]
[129 270 370 470 570]


In [19]:
# 배열이 원본(데이터 저장을 위한 자신만의 메모리 공간을 가지고 있는 경우)인지 참조본인지 확인하는법
# 배열의 base 속성
# - None : 자신의 데이터를 따로 가진 경우(copy)
# - 배열 : 자신의 데이터를 따로 가지지 못하는 경우(view)

np_arr=np.array([170,270,370,470,570])
x = np_arr.view()
y = np_arr.copy()

print(x.base)
print(y.base)

[170 270 370 470 570]
None


# NumPy 배열의 Shape
- shape 속성은 각 차원의 원소 개수

In [20]:
# 배열 형태 알아보기
np_arr=np.array([[101,201,301,401],[501,601,701,801]])
shape = np_arr.shape
print(shape)
print(type(shape))
print(len(shape))

# 실습1 : 각 행의 원소 갯수가 다른 경우 출력?
# 배열 형태(차원) 지정하기

np_arr = np.array([101,201,301,401,501],ndmin=5)
print(np_arr)
print('배열의 모양 : ',np_arr.shape)

(2, 4)
<class 'tuple'>
2
[[[[[101 201 301 401 501]]]]]
배열의 모양 :  (1, 1, 1, 1, 5)


# 배열 ReShaping (재구성, 차원 변경)
- reshape 는 배열의 형태를 바꾸는 것
- shape 은 각 차원의 원소 갯수라고 정의되었으므로 reshape 한다는 것은 차원을 증감하거나 원소 갯수를 증감하는 것

In [22]:
# 1차원 -> 2차원
np_arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = np_arr.reshape(3,4) # 3*4 = 12
print(newarr)
print()

# 1차원 -> 3차원
np_arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr =np_arr.reshape(2,2,3) # 2*2*3 = 12
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [24]:
# reshape 갯수가 안 맞으면?
np_arr=np.array([1,2,3,4,5,6,7,8])
newarr = np_arr.reshape(3,3) #3*3 = 9로 안됨 커서 안됨
print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [25]:
# reshape 된 배열은 copy 일까 view 일까?
np_arr=np.array([1,2,3,4,5,6,7,8])
print(np_arr.reshape(2,4).base) 

# none 은 copy
# 데이터가 나오면 view

[1 2 3 4 5 6 7 8]


In [30]:
# 차원을 모르는 배열???
# -1 은 한군데만 써야함
np_arr=np.array([1,2,3,4,5,6,7,8])
print(np_arr.shape)

np_arr=np.array([1,2,3,4,5,6,7,8])
newarr =np_arr.reshape(2,2,-1)
print(newarr.shape)
print(newarr)

#실습 1: -1을 여러곳에 쓰면? 안된다. 
#실습 2: -1 대신 다른 음수를 쓰면?  된다 음수값은 1개만 써야하지만 음수값 1개의 값은 -1 이어도 -5여도 사용 가능함.


(8,)
(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [32]:
# 다차원을 1차원으로 만들기
# shape 크기로 음수(-1) 사용

np_arr=np.array([[1,2,3,4],[5,6,7,8]])

newarr =np_arr.reshape(-1)
print(newarr)

newarr = np_arr.flatten()
print(newarr)

print(newarr.base)      # 리스트는 데이터에 [1 , 2, 3, 4, 5, ]처럼 , 가 붙는다


[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
None


# 3. 판다스 (Pandas) 로 데이터 다루기

# 데이터 과학(Data Science)
- 데이터 과학은 데이터를 연구하는 분야
- 데이터 자체는 데이터 과학에서 가장 중요한 자원
- 주로 빅데이터를 저장, 분석하며 인공지능 기법 활용
- 데이터 분석 업무
    : 데이터 수집 정리에 80~90% 를 할애
    : 분석 프로세스(알고리즘 선택, 모델링,분석,정보추출)에 10~20% 할애

# 3-1 판다스(Pandas) 패키지 기본 개념 익히기 
pandas는 python data analysis library 의 약자로 python 으로 작성된 데이터 조작, 분석 패키지임

    # 개요
    - 데이터에 대한 공통 포맷을 사용해 서로 다른 데이터 형식을 통일해 처리
    - 시리즈(Series; 1차원 배열)와 데이터프레임(DataFrame; 2차원 배열)으로 구성
    - 기술문서 : https://pandas.pydata.org/docs/
    - 요약된 예제 : https://pandas.pydata.org/ 에서 요약 페이퍼(cheat sheet) 검색

# Pandas 사용을 위한 환경 설정
1. 환경설치를 위해 Python Terminal 창을 연다
    -pip (파이썬 관련 패키지 설치에 사용하는 명령어) 업데이트 실행
ex) pip install --upgrade pip
    pip install --upgrade pandas



# 시리즈는 책 12p 참조


In [33]:
# pandas 라이브러리 추가
import pandas as pd

# key : value 형식을 갖는 딕셔너리를 만들고, 변수 dic_data에 저장
dic_data = {'x':7,'y' :77,'z':777}

# 판다스의 Series() 메서드를 사용해 딕셔너리(dic_data)를 시리즈 형식으로 변환한 후 변수 sr_data에 저장
sr_data = pd.Series(dic_data)

#시리즈 sr_data 의 자료형 출력해보기
print(sr_data.dtype)
print()

# 시리즈 sr_data 에 저장된 시리즈 객체를 출력
print(sr_data)

int64

x      7
y     77
z    777
dtype: int64


# 인덱스와 데이터를 배열로 추출하기
- 인덱스 배열 : Series객체.[index]
- 데이터 배열 : Series객체.[values]

In [37]:
import pandas as pd

# 리스트 --> 시리즈 변환 후 sr_data 에 저장
list_data = ['2022-03-10',3.14,'XYZ',10,True]
sr_data = pd.Series(list_data)
print(sr_data)
print()

# 시리즈의 인덱스 배열을 idx 에 저장하고 데이터 값은 배열로 val 에 저장
idx = sr_data.index
val = sr_data.values

print(idx)
print()
print(val)
print()


## 문제 : idx 와 val 의 타입 출력해보기
print('idx 타입 : ',idx.dtype)
print()
print('val 타입 : ',val.dtype)

0    2022-03-10
1          3.14
2           XYZ
3            10
4          True
dtype: object

RangeIndex(start=0, stop=5, step=1)

['2022-03-10' 3.14 'XYZ' 10 True]

idx 타입 :  int64

val 타입 :  object


# 시리즈의 요소 (element) 선택
- 하나 또는 특정 범위 요소를 선택할 수 있음
- 파이썬의 리스트 슬라이싱 기법 활용
- 지정 방법
    정수형 위치 인덱스 : [정수형 숫자]
    인덱스 이름 : ["이름"] 또는 ['이름']

In [39]:
import pandas as pd

#튜플을 시리즈로 변환 (index 옵션에 리스트 형식으로 인덱스로 사용할 이름을 지정)
tuple_data = ('경민','2022-03-10','남',True)
sr_data = pd.Series(tuple_data, index=['이름','생일','성별','학생 여부'])
print(sr_data)
print()

# 원소 한

이름               경민
생일       2022-03-10
성별                남
학생 여부          True
dtype: object

object


# 13p