#빅데이터분석
##빅데이터 분석

'''python code 블럭 주석'''

In [2]:
# numpy를 사용하기 위해 lib 추가
# 프로그램에서는 np로 별칭을 사용한다고 선언

import numpy as np

np_arr = np.array(['101.5',202,303,404,505])
print(np_arr)
print(type(np_arr))
print(np_arr.dtype)


['101.5' '202' '303' '404' '505']
<class 'numpy.ndarray'>
<U11


#배열의 차원

In [4]:
#0-D array
np_arr = np.array(129)
print(np_arr,'\n')

#1-D array
np_arr = np.array([101,202,303,404,505])
print(np_arr,'\n')

#2-D array
#1-D array들을 원소로 가지는 array
#2nd order tensor 라고 함
np_arr = np.array([[101,202,303],[404,505,606]])
print(np_arr)
print()

#3-D array
np_arr = np.array([[[101,202,303],[404,505,606],[101,202,303],[404,505,606]]])
print(np_arr)
print()

129 

[101 202 303 404 505] 

[[101 202 303]
 [404 505 606]]

[[[101 202 303]
  [404 505 606]
  [101 202 303]
  [404 505 606]]]



#배열의 차원 검사

In [7]:
#배열의 차원이 몇 차원인지 알아보는 코드
# 배열 구성할 때 [] 의 내포 관계를 잘 살펴보면 차원을 알 수 있음

dim_0 = np.array(129)
dim_1 = np.array([170,270,370,470,570,670])
dim_2 = np.array([[170,270,370],[470,570,670]])
dim_3 = np.array([[[170,270,370],[44,55,66],[110,220,330],[404,505,606]]])


# ~ . ndim 은 ~이 몇 차원인지 알려줌
print(dim_0.ndim)
print()
print(dim_1.ndim)
print()
print(dim_2.ndim)
print()
print(dim_3.ndim)
print()


0

1

2

3



#고차원 배열 생성

In [8]:
# [] 내포관계 상관 없이 고차원 배열 생성
# array() 메서드의 매개변수 ndim에 생성할 차원을 직접 지정

np_arr =np.array([170,270,370,470],ndmin=5)
print(np_arr)
print()
print("차원의 수 : ",np_arr.ndim)

[[[[[170 270 370 470]]]]]

차원의 수 :  5


#배열 인덱싱